const Skills = () => {
  return (
    <div className="flex flex-wrap justify-center gap-2 mt-2">
      <div>
        <img
          src="https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white"
          alt="HTML5"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white"
          alt="CSS3"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E"
          alt="JavaScript"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/typescript-%23007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white"
          alt="TypeScript"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/react-%2320232a.svg?style=for-the-badge&logo=react&logoColor=%2361DAFB"
          alt="React"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/Next-black?style=for-the-badge&logo=next.js&logoColor=white"
          alt="Next.js"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/redux-%23593d88.svg?style=for-the-badge&logo=redux&logoColor=white"
          alt="Redux"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/tailwindcss-%2338B2AC.svg?style=for-the-badge&logo=tailwind-css&logoColor=white"
          alt="Tailwind CSS"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/SASS-hotpink.svg?style=for-the-badge&logo=SASS&logoColor=white"
          alt="SASS"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/webpack-%238DD6F9.svg?style=for-the-badge&logo=webpack&logoColor=black"
          alt="Webpack"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/git-%230769AD.svg?style=for-the-badge&logo=git&logoColor=white&color=orange"
          alt="Git"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/markdown-%23000000.svg?style=for-the-badge&logo=markdown&logoColor=white"
          alt="Markdown"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54"
          alt="Python"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/jquery-%230769AD.svg?style=for-the-badge&logo=jquery&logoColor=white"
          alt="jQuery"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/JWT-black?style=for-the-badge&logo=JSON%20web%20tokens"
          alt="JWT"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/MongoDB-%234ea94b.svg?style=for-the-badge&logo=mongodb&logoColor=white"
          alt="MongoDB"
        />
      </div>
      <div>
        <img
          src="https://img.shields.io/badge/mysql-%2300000f.svg?style=for-the-badge&logo=mysql&logoColor=white"
          alt="MySQL"
        />
      </div>
    </div>
  )
}

export default Skills
